### ISSUE TITLE
Data Not getting posted with redirect.

### ISSUE THREAD

**Issue by sambatesdesign** [harrycresswell/zapier-contact-form#1]
I can get this working fine without the js but when I add the JS I get redirected, yet the data is not getting sent to zapier? I tried using the demo code same issue

**Comment by harrycresswell** [comment]
When you switch to the Ajax method you will have to test the webhook again in Zapier, to pull in new sample data. Then make sure update your email template with the new data, then turn your Zap back on. I’m not entirely sure why this is happening now, it never used to but that should fix it for you.
